### ISSUE TITLE
Find other entities

### ISSUE THREAD

**Issue by kimikomotoyama** [cc5-team-red/zenni#2]
Anthony finds other live entities to get information
 
As a citizen of Tokyo in a disaster relief, 
I want to find the other entity on the map
So that I can get information on how to help others in need.

---

## Acceptance Criteria:
- [ ] replace icon so that people intuitively know it's another human.

**Comment by TsubasaK111** [comment]
- [ ] replace icon so that people intuitively know it's another human.
